aes:
  encryption:
    key: this-is-test-key  
    
spring:
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/electioncampaign
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:Orive@123}
#    url: jdbc:mysql://database-1.c10ku28k2ttw.ap-south-1.rds.amazonaws.com:3306/electioncampaign
#    username: admin
#    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: SEURITY-SERVICE   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB        
  mail:
    host: smtp.gmail.com
    port: 587
    username: hr.orivesolutions@gmail.com
    password: ieyh njde yroo ebij
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  
    smtp:
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      auth: true
      starttls:
        enable: true
      ssl:
        enable: false
    debug: true
    
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
twilio:
  account:
    sid: AC9ce2e24fa85428c738462b5df8f468f4
  auth:
    token: 14e6154eb137fed37a0764eeb2466f6c
  from:
    number: +16502001838 
otp:
  length: 6